// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUabo9pU57N427I5fORhj3T27ravpTzy8',
    appId: '1:404900933629:web:b9bd4b0b373ab3c3f9b394',
    messagingSenderId: '404900933629',
    projectId: 'myebooksapp123',
    authDomain: 'myebooksapp123.firebaseapp.com',
    storageBucket: 'myebooksapp123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPMjOeOO7emoLY3A3zfnXDH2m9oUKNYAY',
    appId: '1:404900933629:android:51fa16c0e81bdc6ff9b394',
    messagingSenderId: '404900933629',
    projectId: 'myebooksapp123',
    storageBucket: 'myebooksapp123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcLXBuJ9ywWf87rIy-AEm6PNMNxUufddc',
    appId: '1:404900933629:ios:abf7e4bf45e35dfcf9b394',
    messagingSenderId: '404900933629',
    projectId: 'myebooksapp123',
    storageBucket: 'myebooksapp123.appspot.com',
    iosBundleId: 'com.ebook.ebooksapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcLXBuJ9ywWf87rIy-AEm6PNMNxUufddc',
    appId: '1:404900933629:ios:6faa9b7c5a72c3e1f9b394',
    messagingSenderId: '404900933629',
    projectId: 'myebooksapp123',
    storageBucket: 'myebooksapp123.appspot.com',
    iosBundleId: 'com.ebook.ebooksapp.RunnerTests',
  );
}
