List<Map<String, dynamic>> books = [
  {
    "id": 1,
    "book_name": "Ikigai",
    "author_name": "Francesc Miralles",
    "category": "personal development",
    "year": 2016,
    "image": "assets/images/b1.jpg",
    "pages": 359,
    "content": "They say people remember important moments in their life well, yet no one even remembers their own birth. If you like tuna and tomato sauce, try combining the two, it’s really not as bad as it sounds. I know many children ask for a pony, but I wanted a bicycle with rockets strapped to it. Erin accidentally created a new universe.Dan ate the clouds like cotton candy.They say people remember important moments in their life well, yet no one even remembers their own birth. If you like tuna and tomato sauce, try combining the two, it’s really not as bad as it sounds. I know many children ask for a pony, but I wanted a bicycle with rockets strapped to it. Erin accidentally created a new universe.Dan ate the clouds like cotton candy."
  },
  {
    "id": 2,
    "book_name": "The Power of your subconscious mind",
    "author_name": "Joseph Murphy",
    "category": "personal development",
    "year": 1963,
    "image": "assets/images/b2.jpg",
    "pages": 359,
    "content": "Best friends are like old tomatoes and shoelaces.The sudden rainstorm washed crocodiles into the ocean.Gwen had her best sleep ever on her new bed of nails.Best friends are like old tomatoes and shoelaces.The sudden rainstorm washed crocodiles into the ocean.Gwen had her best sleep ever on her new bed of nails.",
  },
  {
    "id": 3,
    "book_name": "Atomic Habits",
    "author_name": "James Clear",
    "category": "personal development",
    "year": 2018,
    "image": "assets/images/b3.jpg",
    "pages": 359,
    "content": "I was fishing for compliments and accidentally caught a trout.Harrold felt confident that nobody would ever suspect his spy pigeon.Combines are no longer just for farms.",
  },
  {
    "id": 4,
    "book_name": "It Ends with Us",
    "author_name": "Colleen Hoover",
    "category": "romance",
    "year": 2016,
    "image": "assets/images/b4.jpg",
    "pages": 359,
    "content": "The book is in front of the table.She had convinced her kids that any mushroom found on the ground would kill them if they touched it.I am happy to take your donation; any amount will be greatly appreciated.",
  },
  {
    "id": 5,
    "book_name": "It Starts with Us",
    "author_name": "Colleen Hoover",
    "category": "romance",
    "year": 2022,
    "image": "assets/images/b5.jpg",
    "pages": 359,
    "content": "Joe made the sugar cookies; Susan decorated them.Peter found road kill an excellent way to save money on dinner.As you consider all the possible ways to improve yourself and the world, you notice John Travolta seems fairly unhappy.",
  },
  {
    "id": 6,
    "book_name": "The Villa",
    "author_name": "Rachel Hawkins",
    "category": "mystery",
    "year": 2023,
    "image": "assets/images/b6.jpg",
    "pages": 359,
    "content": "The book is in front of the table.I honestly find her about as intimidating as a basket of kittens.He decided that the time had come to be stronger than any of the excuses he'd used until then.",
  },
  {
    "id": 7,
    "book_name": "In The Woods",
    "author_name": "Tana French",
    "category": "mystery",
    "year": 2007,
    "image": "assets/images/b7.jpg",
    "pages": 359,
    "content": "Last Friday I saw a spotted striped blue worm shake hands with a legless lizard.I only enjoy window shopping when the windows are transparent.As she walked along the street and looked in the gutter, she realized facemasks had become the new cigarette butts.",
  },
  {
    "id": 8,
    "book_name": "Then She was Gone",
    "author_name": "Lisa Jewell",
    "category": "thriller",
    "year": 2017,
    "image": "assets/images/b8.jpg",
    "pages": 359,
    "content": "You should never take advice from someone who thinks red paint dries quicker than blue paint.Sarah ran from the serial killer holding a jug of milk.The skeleton had skeletons of his own in the closet.",
  },
  {
    "id": 9,
    "book_name": "The Buried Giant",
    "author_name": "Kazuo Ishiguro",
    "category": "fantasy",
    "year": 2015,
    "image": "assets/images/b9.jpg",
    "pages": 359,
    "content": "There are few things better in life than a slice of pie.The miniature pet elephant became the envy of the neighborhood.He looked behind the door and didn't like what he saw.",
  },
  {
    "id": 10,
    "book_name": "The Colour of Magic",
    "author_name": "Terry Pratchett",
    "category": "fantasy",
    "year": 1983,
    "image": "assets/images/b10.jpg",
    "pages": 359,
    "content": "He stepped gingerly onto the bridge knowing that enchantment awaited on the other side.He strives to keep the best lawn in the neighborhood.It isn't true that my mattress is made of cotton candy.",
  },
  {
    "id": 11,
    "book_name": "A Voyage For Madmen",
    "author_name": "Peter Nichols",
    "category": "adventure",
    "year": 2001,
    "image": "assets/images/b11.jpg",
    "pages": 359,
    "content": "Garlic ice-cream was her favorite.Two seats were vacant.Of course, she loves her pink bunny slippers.",
  },
  {
    "id": 12,
    "book_name": "Dear Life",
    "author_name": " Alice Munro",
    "category": "short stories",
    "year": 2012,
    "image": "assets/images/b12.jpg",
    "pages": 359,
    "content": "Karen realized the only way she was getting into heaven was to cheat.The murder hornet was disappointed by the preconceived ideas people had of him.Each person who knows you has a different perception of who you are.",
  },
];
